#9 Sprint 9
KazariaFenix/java-filmorate pull request #4
Opened 2023-07-19 19:04 UTC by KazariaFenix

2023-07-19 21:14 UTC, KazariaFenix commented
Добавлен необходимый функционал проекта

2023-07-20 17:10 UTC, alexache requested changes

2023-07-20 17:10 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        manager.buildFilm(film);
Для чего то делать в 2 метода, а не одним единственным в менеджере?

2023-07-20 17:10 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    @Getter
Для чего эта аннотация?

2023-07-20 17:10 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmManager.java
> +
Немного бедный класс, не хватает какого-то функционала

2023-07-20 17:10 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/validator/PastValidator.java
> +    String validDate;
Тоже не хватает модификатора доступа

2023-07-20 17:10 UTC, alexache commented on src/test/java/ru/yandex/practicum/filmorate/usertest/FilmTest.java
> +public class FilmTest {
В данном спринте можно было обойтись немного более простыми тестами, но почему бы и нет, раз уже написано

2023-07-20 17:28 UTC, KazariaFenix commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    FilmManager manager = new FilmManager();
Исправлено

2023-07-20 17:31 UTC, KazariaFenix commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        return new ArrayList<>(manager.getFilmMap().values());
Исправлено

2023-07-20 17:34 UTC, KazariaFenix commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (manager.getFilmMap().keySet().contains(film.getId())) {
Исправлено

2023-07-20 17:38 UTC, KazariaFenix commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        manager.buildFilm(film);
Исправлено

2023-07-20 17:40 UTC, KazariaFenix commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    @Getter
Тесты не сразу получились, экспериментировал, потом забыл убрать, моя вина)

2023-07-20 17:41 UTC, KazariaFenix commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmManager.java
> +
Исправлено

2023-07-20 17:42 UTC, KazariaFenix commented on src/main/java/ru/yandex/practicum/filmorate/validator/PastValidator.java
> +    String validDate;
Исправлено

2023-07-20 18:03 UTC, KazariaFenix commented
Исправил все недочеты и перенес функциональность

2023-07-21 10:01 UTC, alexache approved these changes

2023-07-21 14:03 UTC, merged

2023-07-21 15:07 UTC, KazariaFenix commented
Объединение первой ветки