feat: добавление функционала согласно ТЗ
KazariaFenix/java-filmorate pull request #5
Opened 2023-08-02 19:42 UTC by KazariaFenix

2023-08-02 20:22 UTC, KazariaFenix commented
feat: добавление функционала согласно финального задания спринта

2023-08-03 13:47 UTC, mikita95 requested changes
Все сделано хорошо. Оставил несколько небольших замечаний :)

2023-08-03 13:47 UTC, mikita95 commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryUserStorage.java
> +        return userMap;
Так выдавать ссылку на внутреннее поле - не совсем верно, так можно поменять эту коллекцию снаружи. Лучше просто добавить в хранилище метод получения объекта по id

2023-08-03 13:47 UTC, mikita95 commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryUserStorage.java
> +        if (!userMap.keySet().contains(user.getId())) {
Можно использовать метод containsKey

2023-08-03 13:47 UTC, mikita95 commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +    public Map<Integer, Film> getFilmMap() {
Так выдавать ссылку на внутреннее поле - не совсем верно, так можно поменять эту коллекцию снаружи. Лучше просто добавить в хранилище метод получения объекта по id

2023-08-03 13:47 UTC, mikita95 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    private final InMemoryFilmStorage filmStorage;
Здесь нужно использовать интерфейс хранилища, а не его реализацию

2023-08-03 13:47 UTC, mikita95 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public FilmService(InMemoryUserStorage userStorage, InMemoryFilmStorage filmStorage) {
Здесь нужно использовать интерфейс хранилища, а не его реализацию

2023-08-03 13:47 UTC, mikita95 commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    InMemoryUserStorage storage;
Не хватает модификатора доступа. Здесь нужно использовать интерфейс хранилища, а не его реализацию

2023-08-03 13:47 UTC, mikita95 commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    UserService(InMemoryUserStorage storage) {
Здесь нужно использовать интерфейс хранилища, а не его реализацию

2023-08-03 13:47 UTC, mikita95 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private final InMemoryFilmStorage storage;
Лучше в контроллере оставить лишь сервис, а уже сервис будет общаться с хранилищем. Так проще настроить тестирование, валидацию и тд, а также добавить какую-то бизнес-логику

2023-08-03 14:43 UTC, KazariaFenix commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryUserStorage.java
> +        return userMap;
Исправлено

2023-08-03 15:15 UTC, KazariaFenix commented
Исправления после первого ревью)

2023-08-04 16:41 UTC, mikita95 approved these changes
Всё хорошо. Можно мержить пул-реквест

2023-08-20 07:36 UTC, merged